import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#a8cbe4",
        "surface-dim": "#131313",
        "on-secondary-container": "#b7b5b4",
        "tertiary-container": "#c2e6ff",
        "primary-fixed": "#c9f236",
        "background": "#131313",
        "secondary-fixed-dim": "#c8c6c5",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#c5c9ae",
        "error": "#ffb4ab",
        "pure-black": "#000000",
        "on-tertiary-fixed": "#001e2d",
        "on-background": "#e5e2e1",
        "outline": "#8f937b",
        "status-warning": "#FFB800",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#444934",
        "secondary": "#c8c6c5",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-primary": "#526600",
        "tertiary": "#fefdff",
        "on-tertiary-fixed-variant": "#274b5f",
        "secondary-fixed": "#e5e2e1",
        "surface-container": "#201f1f",
        "surface": "#131313",
        "on-primary-fixed-variant": "#3d4d00",
        "primary-fixed-dim": "#aed50d",
        "on-error-container": "#ffdad6",
        "on-secondary": "#313030",
        "primary-container": "#c8f135",
        "tertiary-fixed": "#c5e7ff",
        "secondary-container": "#474746",
        "text-muted": "#888888",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#171e00",
        "on-tertiary": "#0c3447",
        "primary": "#ffffef",
        "border-subtle": "#333333",
        "on-surface": "#e5e2e1",
        "on-tertiary-container": "#45687d",
        "on-primary-container": "#566c00",
        "surface-container-lowest": "#0e0e0e",
        "on-primary": "#293500",
        "surface-bright": "#3a3939",
        "on-secondary-fixed-variant": "#474746",
        "surface-tint": "#aed50d",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "button-height-heavy": "5rem",
        "gutter": "1rem",
        "container-margin": "1.5rem",
        "button-height-standard": "3.5rem",
        "touch-target-min": "2.75rem",
        "stack-gap-lg": "2rem",
      },
      fontFamily: {
        "display-lg": ["Bebas Neue", "sans-serif"],
        "headline-md": ["Bebas Neue", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Bebas Neue", "sans-serif"],
        "display-giant": ["Bebas Neue", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "64px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "36px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-giant": ["120px", { lineHeight: "110px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
